
function Trim$_String_(s){return s.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}
var TObject={$ClassName:"TObject",$Parent:null,ClassName:function(s){return s.$ClassName},ClassType:function(s){return s},ClassParent:function(s){return s.$Parent},$Init:function(s){},Create:function(s){return s},Destroy:function(s){for(var prop in s)if(s.hasOwnProperty(prop))delete s[prop]},Destroy$:function(s){return s.ClassType.Destroy(s)},Free:function(s){if(s!==null)s.ClassType.Destroy(s)}}
function $VarToBool(v){return!!(typeof v=="string"?{"1":1,"t":1,"y":1,"true":1}[v.toLowerCase()]:v)}
function $New(c){var i={ClassType:c};c.$Init(i);return i}
function RunResearch(){var ceil=0;GFs=require("fs");GCrashAfter=(process.argv[2]!==undefined)?parseInt(process.argv[2],10):-1;ceil=process.env.CEILING?parseInt(process.env.CEILING,10):200000;GStore=JW3DataStore.Create$6($New(JW3DataStore));GPack={corroborationByGrade:{LOW:2,MEDIUM:2,HIGH:3},claimTypeRequiresTier:{disease:1,therapeutic:1,'structure-function':2}};GLedger=TLedger.Create$5($New(TLedger),GStore,GPack,"runner");GBudget=TBudget.Create$7($New(TBudget),GStore,ceil);TBudget.OnTrip(GBudget,function(){console.log("  >> BREAKER TRIPPED")});GProcessedThisRun=0;if(CheckpointExists()){TLedger.LoadJSON(GLedger,ReadCheckpoint());console.log("Resuming from checkpoint: "+TLedger.ClaimCount(GLedger).toString()+" claim(s).");DoGatherNext(0)}else{console.log("Fresh run. Proxy http:\/\/localhost:3030, ceiling "+ceil.toString()+" tok.");DoPlan()}}
function YN(b){var R="";if(b){R="yes"}else R="no";return R}
function WriteSynth(AText){GFs.writeFileSync(".\/research-synthesis.md",AText)}
function VSrcVerified(a,i$4){var R=false;R=((a)[i$4]&&(a)[i$4].verified===true);return R}
function VSrcUrl(a,i$4){var R="";R=String(((a)[i$4]&&(a)[i$4].url)||'');return R}
function VSrcTier(a,i$4){var R=0;R=((a)[i$4]&&(a)[i$4].tier)||5;return R}
function VSrcOrigin(a,i$4){var R="";R=String(((a)[i$4]&&(a)[i$4].origin)||'');return R}
function VerifySources(AGather,OnDone){var srcs=((AGather)&&(AGather).sources)||[];var checks=srcs.map(function(s){var url=s&&s.url;if(!url){s.verified=false;return Promise.resolve(s)}
return fetch(url,{method:'GET',signal:AbortSignal.timeout(8000)}).then(function(r){s.verified=!!(r&&r.ok);return s}).catch(function(){s.verified=false;return s})});Promise.all(checks).then(function(arr){(OnDone)(arr)})}
function SaveCheckpoint(){GFs.writeFileSync(".\/research-ledger.json",TLedger.ToJSON(GLedger))}
function ResultText(AData){var R="";R=String(((AData)&&(AData).text)||'');return R}
function ResultOut(AData){var R=0;R=((AData)&&(AData).usage&&(AData).usage.outputTokens)||0;return R}
function ResultIn(AData){var R=0;R=((AData)&&(AData).usage&&(AData).usage.inputTokens)||0;return R}
function ReadCheckpoint(){var R="";R=String(GFs.readFileSync(".\/research-ledger.json","utf8"));return R}
function PostJSONNode(AUrl,ABody,OnResult,OnError){fetch(AUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:ABody}).then(function(resp){return resp.text().then(function(t){return{ok:resp.ok,status:resp.status,text:t}})}).then(function(x){if(x.ok){var d;try{d=JSON.parse(x.text)}catch(e){(OnError)(x.status,'bad JSON from proxy');return}
(OnResult)(d)}else{(OnError)(x.status,x.text||'HTTP error')}}).catch(function(e){(OnError)(0,String((e&&e.message)||e))})}
function PassStr(b){var R="";if(b){R="PASS"}else R="blocked";return R}
function ParseJsonLoose(AText){var R=undefined;var s=String(AText||'');var a=s.indexOf('[');var o=s.indexOf('{');var start=-1;if(a===-1)start=o;else if(o===-1)start=a;else start=Math.min(a,o);var endA=s.lastIndexOf(']');var endO=s.lastIndexOf('}');var fin=Math.max(endA,endO);var r=null;if(start!==-1&&fin!==-1&&fin>start){try{r=JSON.parse(s.slice(start,fin+1))}catch(e){r=null}}
R=r;return R}
function JsonOk(v$2){var R=false;R=((v$2)!==null&&(v$2)!==undefined);return R}
function ItemStr(a,i$4,f){var R="";R=String(((a)[i$4]&&(a)[i$4][f])||'');return R}
function Finish(){console.log("Done. Ledger holds "+TLedger.ClaimCount(GLedger).toString()+" claim(s); checkpoint at .\/research-ledger.json.")}
function FieldStr(o,f){var R="";R=String(((o)&&(o)[f])||'');return R}
function FieldBool(o,f){var R=false;R=((o)&&(o)[f]===true);return R}
function DoSynthesize(){var arr=undefined,n=0,i=0,st="",body="",sys="";arr=ClaimsJson();n=ArrLen(arr);body="";var $t1;for(i=0,$t1=n;i<$t1;i++){st=ClaimStatusAt(arr,i);if(st=="finding"||st=="published")body+="- "+ClaimTextAt(arr,i)+"\n"}
if(body==""){console.log("No findings cleared the gates; nothing to synthesise.");Finish();return}
sys="You are a research writer. Given the verified findings, write a brief, plain, well-calibrated synthesis of two short paragraphs. State uncertainty honestly. No headings.";CallModel("claude-sonnet-4-6",sys,"Findings:\n"+body,!1,function(Data){TBudget.RecordUsage(GBudget,ResultIn(Data),ResultOut(Data));WriteSynth(ResultText(Data));console.log("Synthesis written to .\/research-synthesis.md  [meter "+TBudget.Total(GBudget).toString()+" tok]");Finish()},function(Status,Msg){console.log("Synthesis call failed ("+Status.toString()+"): "+Msg);Finish()})}
function DoPlan(){var sys$1="";console.log("Planning: "+"The effects of extended screen time on children's attention and development.");sys$1="You are a research planner. Break the subject into 3 to 5 specific, checkable factual claims worth investigating. Phrase each claim at the strength the evidence can bear: prefer associational or descriptive wording such as \"is associated with\", \"studies report\", or \"the evidence is mixed on\", over causal wording such as \"causes\" or \"leads to\", unless the subject plausibly has randomised or experimental evidence. Do not overstate. Reply with ONLY a JSON array; each element {\"claim\": string, \"species\": one of \"scientific\",\"marketing\",\"regulatory\",\"forecast\"}. No prose, no code fences.";CallModel("claude-sonnet-4-6",sys$1,"The effects of extended screen time on children's attention and development.",!1,function(Data){var plan=undefined,n$1=0,i$1=0,txt="",sp="";TBudget.RecordUsage(GBudget,ResultIn(Data),ResultOut(Data));plan=ParseJsonLoose(ResultText(Data));n$1=ArrLen(plan);if(!n$1){console.log("Planner returned no parseable claims; stopping.");return}
var $t2;for(i$1=0,$t2=n$1;i$1<$t2;i$1++){txt=Trim$_String_(ItemStr(plan,i$1,"claim"));sp=Trim$_String_(ItemStr(plan,i$1,"species"));if(sp=="")sp="scientific";if(txt!="")TLedger.AddClaim(GLedger,txt,sp)}
SaveCheckpoint();console.log("Planned "+TLedger.ClaimCount(GLedger).toString()+" lead(s)  [meter "+TBudget.Total(GBudget).toString()+" tok]");if(TBudget.Tripped(GBudget)){console.log("Halted by breaker after planning.");return}
DoGatherNext(0)},function(Status,Msg){console.log("Plan call failed ("+Status.toString()+"): "+Msg)})}
function DoGatherNext(AStart){var arr$1=undefined,n$2=0,i$2=0,st$1="";arr$1=ClaimsJson();n$2=ArrLen(arr$1);i$2=AStart;while(i$2<n$2){st$1=ClaimStatusAt(arr$1,i$2);if(st$1=="lead"){DoGatherForClaim(i$2,ClaimIdAt(arr$1,i$2),ClaimTextAt(arr$1,i$2));return}
i$2+=1}
DoSynthesize()}
function DoGatherForClaim(AIndex,AId,AText){var sys$2="";console.log("Gathering for lead "+AIndex.toString()+": "+AText);sys$2="You are a research gatherer with web search. Search for the real evidence on the claim and report it HONESTLY: classify by what the claim actually asserts and what you find, never to pass a test. Reply with ONLY a JSON object: {\"claimType\": one of \"disease\",\"therapeutic\",\"structure-function\",\"\" (use \"disease\" or \"therapeutic\" ONLY for a genuine causal medical claim for which you found randomised or controlled evidence; otherwise use \"\"), \"causalBasis\": one of \"interventional\",\"observational\",\"mechanism\",\"none\",\"n\/a\" (use \"interventional\" ONLY if randomised or controlled evidence exists, else \"observational\" for correlational evidence), \"steelman\": the single strongest opposing reading, \"regulatoryStatus\": string if a regulatory claim else \"\", \"predictionsTested\": boolean, \"sources\": [{\"tier\": 1-5 (1=systematic review or RCT, 2=peer-reviewed study, 3=reputable report, 4=primary document, 5=social post), \"origin\": short independence key, \"url\": a real URL you found}]}. Include at least two independent sources with real URLs; prefer a Tier-1 systematic review when one exists. No prose, no code fences.";CallModel("claude-haiku-4-5-20251001",sys$2,"Claim: "+AText,!0,function(Data){var g=undefined,searched=!1;TBudget.RecordUsage(GBudget,ResultIn(Data),ResultOut(Data));searched=((Data)&&(Data).webSearchUsed===true);g=ParseJsonLoose(ResultText(Data));if(!(JsonOk(g))){g={}}
ApplyGatherFields(AId,g);VerifySources(g,function(AVer){var i$3=0,n$3=0,okc=0,v$1={Pass:false,Reasons:""};n$3=ArrLen(AVer);okc=0;var $t3;for(i$3=0,$t3=n$3;i$3<$t3;i$3++){TLedger.AddSourceVerified(GLedger,AId,VSrcTier(AVer,i$3),VSrcOrigin(AVer,i$3),"",VSrcUrl(AVer,i$3),VSrcVerified(AVer,i$3));if(VSrcVerified(AVer,i$3))okc+=1}
v$1=TLedger.Promote(GLedger,AId);SaveCheckpoint();console.log("  lead "+AIndex.toString()+" promote: "+PassStr(v$1.Pass)+"  (web="+YN(searched)+", "+okc.toString()+"\/"+n$3.toString()+" sources verified)  [meter "+TBudget.Total(GBudget).toString()+" tok]");if(!(v$1.Pass))console.log("    blocked: "+v$1.Reasons);GProcessedThisRun+=1;if(TBudget.Tripped(GBudget)){console.log("Halted by breaker; the checkpoint is the handoff.");return}
if(GCrashAfter>0&&GProcessedThisRun>=GCrashAfter){console.log("Simulating crash after "+GProcessedThisRun.toString()+" gather(s); checkpoint saved.");process.exit(1)}
DoGatherNext(AIndex+1)})},function(Status,Msg){console.log("  gather call failed ("+Status.toString()+"): "+Msg+" \u2014 stopping.")})}
function ClaimTextAt(a,i$4){var R="";R=String(((a)[i$4]&&(a)[i$4].text)||'');return R}
function ClaimStatusAt(a,i$4){var R="";R=String(((a)[i$4]&&(a)[i$4].status)||'');return R}
function ClaimsJson(){var R=undefined;var raw="";raw=String(JW3DataStore.Get(GStore,"ledger.claims"));R=raw?JSON.parse(raw):[];return R}
function ClaimIdAt(a,i$4){var R="";R=String(((a)[i$4]&&(a)[i$4].id)||'');return R}
function CheckpointExists(){var R=false;R=!1;if(GFs.existsSync(".\/research-ledger.json"))R=!0;return R}
function CallModel(AModel,ASystem,AUser,AWebSearch,OnResult,OnError){var body$1="";body$1=JSON.stringify({provider:'claude',transport:'api',model:AModel,system:ASystem,messages:[{role:'user',content:AUser}],maxTokens:1500,temperature:0.2,stream:false,webSearch:AWebSearch,providerSessionId:''});PostJSONNode("http:\/\/localhost:3030"+"\/v1\/chat",body$1,OnResult,OnError)}
function ArrLen(a){var R=0;R=(Array.isArray(a)?(a).length:0);return R}
function ApplyGatherFields(AId,AGather){var ct$1="",cb$1="",steel="",regst="";ct$1=Trim$_String_(FieldStr(AGather,"claimType"));cb$1=Trim$_String_(FieldStr(AGather,"causalBasis"));steel=Trim$_String_(FieldStr(AGather,"steelman"));regst=Trim$_String_(FieldStr(AGather,"regulatoryStatus"));if(ct$1!="")TLedger.SetField(GLedger,AId,"claimType",ct$1);if(cb$1!="")TLedger.SetField(GLedger,AId,"causalBasis",cb$1);if(steel!="")TLedger.SetField(GLedger,AId,"steelman",steel);if(regst!="")TLedger.SetField(GLedger,AId,"regulatoryStatus",regst);if(FieldBool(AGather,"predictionsTested"))TLedger.SetField(GLedger,AId,"predictionsTested",!0)}
function Copy$TSubscription(s,d){d.Callback=s.Callback;d.Id=s.Id;d.Key=s.Key;return d}
function Clone$TSubscription($){return{Callback:$.Callback,Id:$.Id,Key:$.Key}}
var JW3DataStore={$ClassName:"JW3DataStore",$Parent:TObject,$Init:function($){TObject.$Init($);$.FChanged=[];$.FKeys=[];$.FNextId=$.FUpdateCount=0;$.FStore$1=undefined;$.FSubs=[]},BeginUpdate:function(S){S.FUpdateCount+=1},Clear:function(S){var snapshot=[];snapshot=S.FKeys;S.FStore$1=TObject.Create($New(TObject));S.FKeys.length=0;for(let i$4=0,$t4=snapshot.length;i$4<$t4;i$4++){JW3DataStore.Notify(S,snapshot[i$4],null)}},Count:function(S){var R=0;R=S.FKeys.length;return R},Create$6:function(S){TObject.Create(S);S.FStore$1=TObject.Create($New(TObject));S.FNextId=1;S.FUpdateCount=0;return S},Delete$1:function(S,Key$1){var idx=0;idx=JW3DataStore.IndexOfKey(S,Key$1);if(idx<0)return;S.FKeys.splice(idx,1);delete S.FStore$1[Key$1];if(S.FUpdateCount>0){JW3DataStore.RecordChange(S,Key$1)}else JW3DataStore.Notify(S,Key$1,null)},Destroy:function(S){S.FSubs.length=0;S.FKeys.length=0;S.FChanged.length=0;TObject.Destroy(S)},EndUpdate:function(S){if(S.FUpdateCount>0)S.FUpdateCount-=1;if(!S.FUpdateCount)JW3DataStore.FlushChanged(S)},FlushChanged:function(S){var val=undefined;for(let i$4=0,$t5=S.FChanged.length;i$4<$t5;i$4++){if(JW3DataStore.Has(S,S.FChanged[i$4])){val=JW3DataStore.Get(S,S.FChanged[i$4])}else val=null;JW3DataStore.Notify(S,S.FChanged[i$4],val)}
S.FChanged.length=0},Get:function(S,Key$1){var R=undefined;if(JW3DataStore.Has(S,Key$1)){R=S.FStore$1[Key$1]}else R=null;return R},Has:function(S,Key$1){var R=false;R=$VarToBool(S.FStore$1.hasOwnProperty(Key$1));return R},IndexOfKey:function(S,Key$1){var R=0;R=-1;for(let i$4=0,$t6=S.FKeys.length;i$4<$t6;i$4++){if(S.FKeys[i$4]==Key$1){R=i$4;return R}}
return R},IndexOfSub:function(S,Id$1){var R=0;R=-1;for(let i$4=0,$t7=S.FSubs.length;i$4<$t7;i$4++){if(S.FSubs[i$4].Id==Id$1){R=i$4;return R}}
return R},Keys:function(S){var R=[];R=S.FKeys;return R},Notify:function(S,Key$1,Value){var Snap=[];Snap=S.FSubs;for(let i$4=0,$t8=Snap.length;i$4<$t8;i$4++){if(Snap[i$4].Key==Key$1||Snap[i$4].Key=="*")Snap[i$4].Callback(Key$1,Value)}},Observe:function(S,Key$1,Callback$1){var R=0;R=JW3DataStore.Subscribe(S,Key$1,Callback$1);if(JW3DataStore.Has(S,Key$1))Callback$1(Key$1,JW3DataStore.Get(S,Key$1));return R},Put:function(S,Key$1,Value){var isNew=false;isNew=!(JW3DataStore.Has(S,Key$1));S.FStore$1[Key$1]=Value;if(isNew){S.FKeys.push(Key$1)}
if(S.FUpdateCount>0){JW3DataStore.RecordChange(S,Key$1)}else JW3DataStore.Notify(S,Key$1,Value)},RecordChange:function(S,Key$1){for(let i$4=0,$t9=S.FChanged.length;i$4<$t9;i$4++){if(S.FChanged[i$4]==Key$1)return}
S.FChanged.push(Key$1)},Subscribe:function(S,Key$1,Callback$1){var R=0;var Sub={Callback:null,Id:0,Key:""};Sub.Id=S.FNextId;Sub.Key=Key$1;Sub.Callback=Callback$1;S.FSubs.push(Clone$TSubscription(Sub));R=S.FNextId;S.FNextId+=1;return R},Unsubscribe:function(S,Id$1){var idx=0;idx=JW3DataStore.IndexOfSub(S,Id$1);if(idx>=0){S.FSubs.splice(idx,1)}},Destroy$:function($){return $.ClassType.Destroy($)}};function Copy$TGateVerdict(s,d){d.Pass=s.Pass;d.Reasons=s.Reasons;return d}
function Clone$TGateVerdict($){return{Pass:$.Pass,Reasons:$.Reasons}}
function SpeciesCSV(AClaim){var R="";var s=((AClaim)&&(AClaim).species)||[];R=Array.isArray(s)?s.join(', '):String(s||'');return R}
function SourceCount(AClaim){var R=0;var s=((AClaim)&&(AClaim).sources)||[];var n=0;for(var i=0;i<s.length;i++){if(s[i]&&s[i].verified!==false)n++}
R=n;return R}
function IndependentCount(AClaim){var R=0;var s=((AClaim)&&(AClaim).sources)||[];var seen={};for(var i=0;i<s.length;i++){if(s[i]&&s[i].verified!==false){var o=s[i].origin;if(o)seen[String(o)]=1}}
R=Object.keys(seen).length;return R}
function HasTier1(AClaim){var R=false;var s=((AClaim)&&(AClaim).sources)||[];var ok=false;for(var i=0;i<s.length;i++){if(s[i]&&s[i].verified!==false&&s[i].tier===1)ok=true}
R=ok;return R}
function ClaimStr(AClaim,AField){var R="";R=String(((AClaim)&&(AClaim)[AField])||'');return R}
function ClaimHasSpecies(AClaim,ASpecies){var R=false;var s=((AClaim)&&(AClaim).species)||[];R=Array.isArray(s)?(s.indexOf(ASpecies)!==-1):(s===ASpecies);return R}
function ClaimBool(AClaim,AField){var R=false;R=((AClaim)&&(AClaim)[AField]===true);return R}
function CheckPromote(AClaim,APack){var R={Pass:false,Reasons:""};var v={Pass:false,Reasons:""},ct="",cb="",need=0;v.Pass=!0;v.Reasons="";ct=ClaimStr(AClaim,"claimType");cb=ClaimStr(AClaim,"causalBasis");if(SourceCount(AClaim)<1)AddReason(v,"[L0] provenance: every claim must cite at least one source.");need=PackCorroboration(APack,ClaimStr(AClaim,"riskGrade"));if(need<2)need=2;if(IndependentCount(AClaim)<need)AddReason(v,"[L0] corroboration: needs "+need.toString()+" independent sources, has "+IndependentCount(AClaim).toString()+".");if(Trim$_String_(ClaimStr(AClaim,"steelman"))=="")AddReason(v,"[L0] steelman: write the strongest opposing reading first.");if(ClaimBool(AClaim,"harmfulInstruction"))AddReason(v,"[L0] no-harm: claim carries a usable harmful instruction.");if(ClaimHasSpecies(AClaim,"scientific")&&(!(HasTier1(AClaim))))AddReason(v,"[domain] a scientific verdict needs a Tier-1 source.");need=PackRequiredTier(APack,ct);if(need<99&&BestTier(AClaim)>need)AddReason(v,"[domain] claim type \""+ct+"\" needs Tier-"+need.toString()+" evidence; best source is Tier-"+BestTier(AClaim).toString()+".");if((ct=="disease"||ct=="therapeutic")&&cb!="interventional")AddReason(v,"[domain] causal claim (\""+ct+"\") rests on "+cb+" evidence, not interventional.");if(ClaimHasSpecies(AClaim,"regulatory")&&Trim$_String_(ClaimStr(AClaim,"regulatoryStatus"))=="")AddReason(v,"[domain] regulatory claim must state register status (listed vs evaluated).");if(ClaimHasSpecies(AClaim,"forecast")&&(!(ClaimBool(AClaim,"predictionsTested"))))AddReason(v,"[domain] forecast\/thesis claim must record dated predictions and test them against outcome.");Copy$TGateVerdict(v,R);return R}
function BestTier(AClaim){var R=0;var s=((AClaim)&&(AClaim).sources)||[];var b=99;for(var i=0;i<s.length;i++){if(s[i]&&s[i].verified!==false){var t=s[i].tier;if(typeof t==='number'&&t<b)b=t}}
R=b;return R}
function PackRequiredTier(APack,AClaimType){var R=0;var m=((APack)&&(APack).claimTypeRequiresTier)||{};var v=m[AClaimType];R=(typeof v==='number')?v:99;return R}
function PackCorroboration(APack,AGrade){var R=0;var c=((APack)&&(APack).corroborationByGrade)||{};var v=c[AGrade];R=(typeof v==='number')?v:2;return R}
function AddReason(V,R$1){V.Pass=!1;if(V.Reasons!="")V.Reasons=V.Reasons+"\n";V.Reasons=V.Reasons+R$1}
var TLedger={$ClassName:"TLedger",$Parent:TObject,$Init:function($){TObject.$Init($);$.FActor="";$.FClaims=$.FEvents=$.FPack=undefined;$.FStore=null},Actor:function(S,AName){S.FActor=AName},AddClaim:function(S,AText,ASpecies){var R="";var id="";id=TLedger.NewId(S);(S.FClaims).push({id:id,text:AText,species:[ASpecies],status:'lead',claimType:'',causalBasis:'n/a',riskGrade:'LOW',sources:[],steelman:'',regulatoryStatus:'',predictionsTested:false,harmfulInstruction:false,signoff:'',actor:S.FActor});TLedger.LogEvent(S,"add",id,ASpecies);TLedger.Sync(S);R=id;return R},AddSource:function(S,AId,ATier,AOrigin,ARef,AUrl){var c=undefined;c=TLedger.GetClaim(S,AId);if(c){(c).sources.push({tier:ATier,origin:AOrigin,ref:ARef,url:AUrl})}
TLedger.LogEvent(S,"source",AId,AOrigin);TLedger.Sync(S)},AddSourceVerified:function(S,AId,ATier,AOrigin,ARef,AUrl,AVerified){var c=undefined;c=TLedger.GetClaim(S,AId);if(c){(c).sources.push({tier:ATier,origin:AOrigin,ref:ARef,url:AUrl,verified:AVerified})}
if(AVerified){TLedger.LogEvent(S,"source",AId,AOrigin)}else TLedger.LogEvent(S,"source-unverified",AId,AOrigin);TLedger.Sync(S)},AddSpecies:function(S,AId,ASpecies){var c=undefined;c=TLedger.GetClaim(S,AId);if(c){if(!Array.isArray((c).species))
(c).species=(c).species?[(c).species]:[];if((c).species.indexOf(ASpecies)===-1)
(c).species.push(ASpecies)}
TLedger.LogEvent(S,"species",AId,ASpecies);TLedger.Sync(S)},ClaimCount:function(S){var R=0;R=(S.FClaims).length;return R},Correct:function(S,AId,ANote){TLedger.SetStatus(S,AId,"corrected");TLedger.LogEvent(S,"correct",AId,ANote);TLedger.Sync(S)},Create$5:function(S,AStore,APack,AActor){TObject.Create(S);S.FStore=AStore;S.FPack=APack;S.FActor=AActor;S.FClaims=[];S.FEvents=[];TLedger.Sync(S);return S},GetClaim:function(S,AId){var R=undefined;var a=S.FClaims;var r=null;for(var i=0;i<a.length;i++){if(a[i]&&a[i].id===AId){r=a[i];break}}
R=r;return R},LoadJSON:function(S,AJson){var o=AJson?JSON.parse(AJson):{};S.FClaims=o.claims||[];S.FEvents=o.events||[];TLedger.Sync(S)},LogEvent:function(S,AType,AId,ADetail){(S.FEvents).push({ts:Date.now(),actor:S.FActor,type:AType,claim:AId,detail:ADetail})},NewId:function(S){var R="";R='c'+Date.now().toString(36)+Math.floor(Math.random()*1000).toString();return R},Promote:function(S,AId){var R={Pass:false,Reasons:""};var c=undefined,v$2={Pass:false,Reasons:""};v$2.Pass=!1;v$2.Reasons="";c=TLedger.GetClaim(S,AId);if(ClaimStr(c,"id")==""){v$2.Reasons="No such claim.";Copy$TGateVerdict(v$2,R);return R}
v$2=CheckPromote(c,S.FPack);if(v$2.Pass){TLedger.SetStatus(S,AId,"finding");TLedger.LogEvent(S,"promote",AId,"finding")}else{TLedger.SetStatus(S,AId,"working");TLedger.LogEvent(S,"promote-blocked",AId,v$2.Reasons)}
TLedger.Sync(S);Copy$TGateVerdict(v$2,R);return R},Publish:function(S,AId,ASignoff){var R=false;var c=undefined;R=!1;if(Trim$_String_(ASignoff)=="")return R;c=TLedger.GetClaim(S,AId);if(ClaimStr(c,"status")!="finding")return R;TLedger.SetField(S,AId,"signoff",ASignoff);TLedger.SetStatus(S,AId,"published");TLedger.LogEvent(S,"publish",AId,ASignoff);TLedger.Sync(S);R=!0;return R},SetField:function(S,AId,AField,AValue){var c=undefined;c=TLedger.GetClaim(S,AId);if(c){(c)[AField]=AValue}
TLedger.Sync(S)},SetStatus:function(S,AId,AStatus){var c=undefined;c=TLedger.GetClaim(S,AId);if(c){(c).status=AStatus}},Sync:function(S){var cj="",ej="";cj=JSON.stringify(S.FClaims);ej=JSON.stringify(S.FEvents);if(!!S.FStore){JW3DataStore.Put(S.FStore,"ledger.claims",cj);JW3DataStore.Put(S.FStore,"ledger.events",ej);JW3DataStore.Put(S.FStore,"ledger.count",TLedger.ClaimCount(S).toString())}
try{localStorage.setItem('research.ledger',cj);localStorage.setItem('research.events',ej)}catch(e){}},ToJSON:function(S){var R="";R=JSON.stringify({claims:S.FClaims,events:S.FEvents},null,2);return R},Destroy:TObject.Destroy};var TBudget={$ClassName:"TBudget",$Parent:TObject,$Init:function($){TObject.$Init($);$.FCalls=$.FCeiling=$.FIn=$.FOut=0;$.FOnTrip=null;$.FStore$2=null;$.FTripped=false},Create$7:function(S,AStore,ACeilingTokens){TObject.Create(S);S.FStore$2=AStore;S.FCeiling=ACeilingTokens;TBudget.Reset$1(S);return S},OnTrip:function(S,ACb){S.FOnTrip=ACb},Publish$1:function(S){if(!S.FStore$2)return;JW3DataStore.Put(S.FStore$2,"meter.inTokens",S.FIn.toString());JW3DataStore.Put(S.FStore$2,"meter.outTokens",S.FOut.toString());JW3DataStore.Put(S.FStore$2,"meter.total",TBudget.Total(S).toString());JW3DataStore.Put(S.FStore$2,"meter.calls",S.FCalls.toString());JW3DataStore.Put(S.FStore$2,"meter.ceiling",S.FCeiling.toString())},RecordUsage:function(S,AInTok,AOutTok){S.FIn+=AInTok;S.FOut+=AOutTok;S.FCalls+=1;TBudget.Publish$1(S);if((!(S.FTripped))&&S.FCeiling>0&&TBudget.Total(S)>S.FCeiling){S.FTripped=!0;if(!!S.FStore$2)JW3DataStore.Put(S.FStore$2,"meter.tripped","true");if(S.FOnTrip)S.FOnTrip()}},Reset$1:function(S){S.FIn=0;S.FOut=0;S.FCalls=0;S.FTripped=!1;TBudget.Publish$1(S);if(!!S.FStore$2)JW3DataStore.Put(S.FStore$2,"meter.tripped","false")},Total:function(S){var R=0;R=S.FIn+S.FOut;return R},Tripped:function(S){var R=false;R=S.FTripped;return R},Destroy:TObject.Destroy};var GFs=undefined,GStore=null,GPack=undefined,GLedger=null,GBudget=null,GProcessedThisRun=0,GCrashAfter=0;RunResearch();